               
(venv) rah@RAHs-iMac RoboPost2 % docker-compose logs bot
robopost-bot  | 2025-07-06 22:51:24,256 - NewsBot - INFO - bot - Starting bot application...
robopost-bot  | 2025-07-06 22:51:24,351 - NewsBot - INFO - bot - Bot service running for admins: [676414834, 259394285]
(venv) rah@RAHs-iMac RoboPost2 % docker-compose logs -f worker
robopost-worker  |  
robopost-worker  |  -------------- celery@0817226cb354 v5.5.3 (immunity)
robopost-worker  | --- ***** ----- 
robopost-worker  | -- ******* ---- Linux-6.10.14-linuxkit-x86_64-with-glibc2.36 2025-07-06 22:51:23
robopost-worker  | - *** --- * --- 
robopost-worker  | - ** ---------- [config]
robopost-worker  | - ** ---------- .> app:         tasks:0x7f294a03af70
robopost-worker  | - ** ---------- .> transport:   redis://redis:6379/0
robopost-worker  | - ** ---------- .> results:     redis://redis:6379/0
robopost-worker  | - *** --- * --- .> concurrency: 2 (prefork)
robopost-worker  | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
robopost-worker  | --- ***** ----- 
robopost-worker  |  -------------- [queues]
robopost-worker  |                 .> celery           exchange=celery(direct) key=celery
robopost-worker  |                 
robopost-worker  | 
robopost-worker  | [tasks]
robopost-worker  |   . tasks.fetch_source_task
robopost-worker  |   . tasks.process_article_task
robopost-worker  |   . tasks.run_all_fetchers_task
robopost-worker  | 
robopost-worker  | [2025-07-06 22:51:24,076: INFO/MainProcess] Connected to redis://redis:6379/0
robopost-worker  | [2025-07-06 22:51:24,083: INFO/MainProcess] mingle: searching for neighbors
robopost-worker  | [2025-07-06 22:51:25,095: INFO/MainProcess] mingle: all alone
robopost-worker  | [2025-07-06 22:51:25,110: INFO/MainProcess] celery@0817226cb354 ready.
robopost-worker  | [2025-07-06 22:51:33,642: INFO/MainProcess] Task tasks.run_all_fetchers_task[89188e7f-bc60-4a32-a52a-9500f3909817] received
robopost-worker  | [2025-07-06 22:51:33,647: INFO/ForkPoolWorker-2] tasks.run_all_fetchers_task[89188e7f-bc60-4a32-a52a-9500f3909817]: Scheduler triggered: Starting to fetch all active sources.
robopost-worker  | [2025-07-06 22:51:33,707: INFO/ForkPoolWorker-2] tasks.run_all_fetchers_task[89188e7f-bc60-4a32-a52a-9500f3909817]: Found 0 active sources to process.
robopost-worker  | [2025-07-06 22:51:33,709: INFO/ForkPoolWorker-2] Task tasks.run_all_fetchers_task[89188e7f-bc60-4a32-a52a-9500f3909817] succeeded in 0.06571670499943139s: None
robopost-worker  | [2025-07-06 22:53:34,827: INFO/MainProcess] Task tasks.run_all_fetchers_task[35f26ddc-228e-4fc3-af63-44a74b3b1780] received
robopost-worker  | [2025-07-06 22:53:34,830: INFO/ForkPoolWorker-2] tasks.run_all_fetchers_task[35f26ddc-228e-4fc3-af63-44a74b3b1780]: Scheduler triggered: Starting to fetch all active sources.
robopost-worker  | [2025-07-06 22:53:34,832: INFO/ForkPoolWorker-2] tasks.run_all_fetchers_task[35f26ddc-228e-4fc3-af63-44a74b3b1780]: Found 1 active sources to process.
robopost-worker  | [2025-07-06 22:53:34,843: INFO/MainProcess] Task tasks.fetch_source_task[7366e293-a322-45bc-aca6-7c3482dd699b] received
robopost-worker  | [2025-07-06 22:53:34,844: INFO/ForkPoolWorker-2] Task tasks.run_all_fetchers_task[35f26ddc-228e-4fc3-af63-44a74b3b1780] succeeded in 0.01546860599955835s: None
robopost-worker  | [2025-07-06 22:53:34,905: INFO/ForkPoolWorker-1] tasks.fetch_source_task[7366e293-a322-45bc-aca6-7c3482dd699b]: Fetching: TechCrunch
robopost-worker  | [2025-07-06 22:53:36,496: INFO/ForkPoolWorker-1] tasks.fetch_source_task[7366e293-a322-45bc-aca6-7c3482dd699b]: NEW ARTICLE from TechCrunch: ‘Improved’ Grok criticizes Democrats and Hollywood’s ‘Jewish executives’
robopost-worker  | [2025-07-06 22:53:36,508: INFO/ForkPoolWorker-1] tasks.fetch_source_task[7366e293-a322-45bc-aca6-7c3482dd699b]: NEW ARTICLE from TechCrunch: At least 36 new tech unicorns were minted in 2025 so far
robopost-worker  | [2025-07-06 22:53:36,520: INFO/ForkPoolWorker-1] tasks.fetch_source_task[7366e293-a322-45bc-aca6-7c3482dd699b]: NEW ARTICLE from TechCrunch: X blocked Reuters accounts in India
robopost-worker  | [2025-07-06 22:53:36,541: INFO/ForkPoolWorker-1] tasks.fetch_source_task[7366e293-a322-45bc-aca6-7c3482dd699b]: NEW ARTICLE from TechCrunch: Researchers seek to influence peer review with hidden AI prompts
robopost-worker  | [2025-07-06 22:53:36,557: INFO/ForkPoolWorker-1] tasks.fetch_source_task[7366e293-a322-45bc-aca6-7c3482dd699b]: NEW ARTICLE from TechCrunch: How Brex is keeping up with AI by embracing the ‘messiness’
robopost-worker  | [2025-07-06 22:53:36,562: INFO/ForkPoolWorker-1] Task tasks.fetch_source_task[7366e293-a322-45bc-aca6-7c3482dd699b] succeeded in 1.7186954709995916s: None
robopost-worker  | [2025-07-06 22:58:31,473: INFO/MainProcess] Task tasks.run_all_fetchers_task[c68db5a0-8189-4b33-a0cb-fa2b9a3a31cb] received
robopost-worker  | [2025-07-06 22:58:31,475: INFO/ForkPoolWorker-2] tasks.run_all_fetchers_task[c68db5a0-8189-4b33-a0cb-fa2b9a3a31cb]: Scheduler triggered: Starting to fetch all active sources.
robopost-worker  | [2025-07-06 22:58:31,477: INFO/ForkPoolWorker-2] tasks.run_all_fetchers_task[c68db5a0-8189-4b33-a0cb-fa2b9a3a31cb]: Found 1 active sources to process.
robopost-worker  | [2025-07-06 22:58:31,480: INFO/MainProcess] Task tasks.fetch_source_task[09526e10-5bc9-4910-bb1c-5c48ad44e818] received
robopost-worker  | [2025-07-06 22:58:31,482: INFO/ForkPoolWorker-2] Task tasks.run_all_fetchers_task[c68db5a0-8189-4b33-a0cb-fa2b9a3a31cb] succeeded in 0.008019158000024618s: None
robopost-worker  | [2025-07-06 22:58:31,484: INFO/ForkPoolWorker-1] tasks.fetch_source_task[09526e10-5bc9-4910-bb1c-5c48ad44e818]: Fetching: TechCrunch
robopost-worker  | [2025-07-06 22:58:32,769: INFO/ForkPoolWorker-1] Task tasks.fetch_source_task[09526e10-5bc9-4910-bb1c-5c48ad44e818] succeeded in 1.2875591709998844s: None
^C
(venv) rah@RAHs-iMac RoboPost2 % 
(venv) rah@RAHs-iMac RoboPost2 % docker-compose logs bot      
robopost-bot  | 2025-07-06 22:51:24,256 - NewsBot - INFO - bot - Starting bot application...
robopost-bot  | 2025-07-06 22:51:24,351 - NewsBot - INFO - bot - Bot service running for admins: [676414834, 259394285]
robopost-bot  | 2025-07-06 22:53:34,719 - NewsBot - INFO - admin_commands - Manual fetch triggered by admin 676414834
robopost-bot  | 2025-07-06 22:53:54,373 - NewsBot - INFO - jobs - Sending article 1 for initial approval.
robopost-bot  | 2025-07-06 22:54:14,370 - NewsBot - INFO - jobs - Sending article 2 for initial approval.
robopost-bot  | 2025-07-06 22:54:25,965 - NewsBot - ERROR - callback_handlers - Error in button_callback for article 1: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
robopost-bot  | Traceback (most recent call last):
robopost-bot  |   File "/app/handlers/callback_handlers.py", line 30, in button_callback
robopost-bot  |     await handle_reject(query, article, db)
robopost-bot  |   File "/app/handlers/callback_handlers.py", line 63, in handle_reject
robopost-bot  |     await query.edit_message_text(text, parse_mode=ParseMode.MARKDOWN_V2, reply_markup=None)
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_callbackquery.py", line 265, in edit_message_text
robopost-bot  |     return await self._get_message().edit_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_message.py", line 3788, in edit_text
robopost-bot  |     return await self.get_bot().edit_message_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 1722, in edit_message_text
robopost-bot  |     return await super().edit_message_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 4293, in edit_message_text
robopost-bot  |     return await self._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 629, in _send_message
robopost-bot  |     result = await super()._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 809, in _send_message
robopost-bot  |     result = await self._post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 697, in _post
robopost-bot  |     return await self._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
robopost-bot  |     return await super()._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 726, in _do_post
robopost-bot  |     result = await request.post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 197, in post
robopost-bot  |     result = await self._request_wrapper(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 374, in _request_wrapper
robopost-bot  |     raise exception
robopost-bot  | telegram.error.BadRequest: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
robopost-bot  | 2025-07-06 22:54:32,277 - NewsBot - ERROR - callback_handlers - Error in button_callback for article 2: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
robopost-bot  | Traceback (most recent call last):
robopost-bot  |   File "/app/handlers/callback_handlers.py", line 30, in button_callback
robopost-bot  |     await handle_reject(query, article, db)
robopost-bot  |   File "/app/handlers/callback_handlers.py", line 63, in handle_reject
robopost-bot  |     await query.edit_message_text(text, parse_mode=ParseMode.MARKDOWN_V2, reply_markup=None)
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_callbackquery.py", line 265, in edit_message_text
robopost-bot  |     return await self._get_message().edit_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_message.py", line 3788, in edit_text
robopost-bot  |     return await self.get_bot().edit_message_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 1722, in edit_message_text
robopost-bot  |     return await super().edit_message_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 4293, in edit_message_text
robopost-bot  |     return await self._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 629, in _send_message
robopost-bot  |     result = await super()._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 809, in _send_message
robopost-bot  |     result = await self._post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 697, in _post
robopost-bot  |     return await self._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
robopost-bot  |     return await super()._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 726, in _do_post
robopost-bot  |     result = await request.post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 197, in post
robopost-bot  |     result = await self._request_wrapper(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 374, in _request_wrapper
robopost-bot  |     raise exception
robopost-bot  | telegram.error.BadRequest: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
robopost-bot  | 2025-07-06 22:54:34,364 - NewsBot - INFO - jobs - Sending article 3 for initial approval.
robopost-bot  | 2025-07-06 22:54:37,966 - NewsBot - ERROR - callback_handlers - Error in button_callback for article 3: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
robopost-bot  | Traceback (most recent call last):
robopost-bot  |   File "/app/handlers/callback_handlers.py", line 30, in button_callback
robopost-bot  |     await handle_reject(query, article, db)
robopost-bot  |   File "/app/handlers/callback_handlers.py", line 63, in handle_reject
robopost-bot  |     await query.edit_message_text(text, parse_mode=ParseMode.MARKDOWN_V2, reply_markup=None)
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_callbackquery.py", line 265, in edit_message_text
robopost-bot  |     return await self._get_message().edit_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_message.py", line 3788, in edit_text
robopost-bot  |     return await self.get_bot().edit_message_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 1722, in edit_message_text
robopost-bot  |     return await super().edit_message_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 4293, in edit_message_text
robopost-bot  |     return await self._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 629, in _send_message
robopost-bot  |     result = await super()._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 809, in _send_message
robopost-bot  |     result = await self._post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 697, in _post
robopost-bot  |     return await self._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
robopost-bot  |     return await super()._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 726, in _do_post
robopost-bot  |     result = await request.post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 197, in post
robopost-bot  |     result = await self._request_wrapper(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 374, in _request_wrapper
robopost-bot  |     raise exception
robopost-bot  | telegram.error.BadRequest: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
robopost-bot  | 2025-07-06 22:54:54,363 - NewsBot - INFO - jobs - Sending article 4 for initial approval.
robopost-bot  | 2025-07-06 22:55:14,365 - NewsBot - INFO - jobs - Sending article 5 for initial approval.
robopost-bot  | 2025-07-06 22:55:37,595 - NewsBot - ERROR - jobs - Exception while handling an update:
robopost-bot  | Traceback (most recent call last):
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1309, in process_update
robopost-bot  |     await coroutine
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_handlers/basehandler.py", line 158, in handle_update
robopost-bot  |     return await self.callback(update, context)
robopost-bot  |   File "/app/handlers/admin_commands.py", line 88, in list_sources
robopost-bot  |     await update.message.reply_text(message, parse_mode=ParseMode.MARKDOWN_V2)
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_message.py", line 1851, in reply_text
robopost-bot  |     return await self.get_bot().send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 2988, in send_message
robopost-bot  |     return await super().send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 1099, in send_message
robopost-bot  |     return await self._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 629, in _send_message
robopost-bot  |     result = await super()._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 809, in _send_message
robopost-bot  |     result = await self._post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 697, in _post
robopost-bot  |     return await self._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
robopost-bot  |     return await super()._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 726, in _do_post
robopost-bot  |     result = await request.post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 197, in post
robopost-bot  |     result = await self._request_wrapper(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 374, in _request_wrapper
robopost-bot  |     raise exception
robopost-bot  | telegram.error.BadRequest: Can't parse entities: character '|' is reserved and must be escaped with the preceding '\'
robopost-bot  | 2025-07-06 22:55:56,239 - NewsBot - ERROR - jobs - Exception while handling an update:
robopost-bot  | Traceback (most recent call last):
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1309, in process_update
robopost-bot  |     await coroutine
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_handlers/basehandler.py", line 158, in handle_update
robopost-bot  |     return await self.callback(update, context)
robopost-bot  |   File "/app/handlers/admin_commands.py", line 88, in list_sources
robopost-bot  |     await update.message.reply_text(message, parse_mode=ParseMode.MARKDOWN_V2)
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_message.py", line 1851, in reply_text
robopost-bot  |     return await self.get_bot().send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 2988, in send_message
robopost-bot  |     return await super().send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 1099, in send_message
robopost-bot  |     return await self._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 629, in _send_message
robopost-bot  |     result = await super()._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 809, in _send_message
robopost-bot  |     result = await self._post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 697, in _post
robopost-bot  |     return await self._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
robopost-bot  |     return await super()._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 726, in _do_post
robopost-bot  |     result = await request.post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 197, in post
robopost-bot  |     result = await self._request_wrapper(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 374, in _request_wrapper
robopost-bot  |     raise exception
robopost-bot  | telegram.error.BadRequest: Can't parse entities: character '|' is reserved and must be escaped with the preceding '\'
robopost-bot  | 2025-07-06 22:55:59,972 - NewsBot - ERROR - callback_handlers - Error in button_callback for article 4: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
robopost-bot  | Traceback (most recent call last):
robopost-bot  |   File "/app/handlers/callback_handlers.py", line 30, in button_callback
robopost-bot  |     await handle_reject(query, article, db)
robopost-bot  |   File "/app/handlers/callback_handlers.py", line 63, in handle_reject
robopost-bot  |     await query.edit_message_text(text, parse_mode=ParseMode.MARKDOWN_V2, reply_markup=None)
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_callbackquery.py", line 265, in edit_message_text
robopost-bot  |     return await self._get_message().edit_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_message.py", line 3788, in edit_text
robopost-bot  |     return await self.get_bot().edit_message_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 1722, in edit_message_text
robopost-bot  |     return await super().edit_message_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 4293, in edit_message_text
robopost-bot  |     return await self._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 629, in _send_message
robopost-bot  |     result = await super()._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 809, in _send_message
robopost-bot  |     result = await self._post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 697, in _post
robopost-bot  |     return await self._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
robopost-bot  |     return await super()._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 726, in _do_post
robopost-bot  |     result = await request.post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 197, in post
robopost-bot  |     result = await self._request_wrapper(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 374, in _request_wrapper
robopost-bot  |     raise exception
robopost-bot  | telegram.error.BadRequest: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
robopost-bot  | 2025-07-06 22:56:02,806 - NewsBot - ERROR - callback_handlers - Error in button_callback for article 5: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
robopost-bot  | Traceback (most recent call last):
robopost-bot  |   File "/app/handlers/callback_handlers.py", line 30, in button_callback
robopost-bot  |     await handle_reject(query, article, db)
robopost-bot  |   File "/app/handlers/callback_handlers.py", line 63, in handle_reject
robopost-bot  |     await query.edit_message_text(text, parse_mode=ParseMode.MARKDOWN_V2, reply_markup=None)
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_callbackquery.py", line 265, in edit_message_text
robopost-bot  |     return await self._get_message().edit_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_message.py", line 3788, in edit_text
robopost-bot  |     return await self.get_bot().edit_message_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 1722, in edit_message_text
robopost-bot  |     return await super().edit_message_text(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 4293, in edit_message_text
robopost-bot  |     return await self._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 629, in _send_message
robopost-bot  |     result = await super()._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 809, in _send_message
robopost-bot  |     result = await self._post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 697, in _post
robopost-bot  |     return await self._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
robopost-bot  |     return await super()._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 726, in _do_post
robopost-bot  |     result = await request.post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 197, in post
robopost-bot  |     result = await self._request_wrapper(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 374, in _request_wrapper
robopost-bot  |     raise exception
robopost-bot  | telegram.error.BadRequest: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
robopost-bot  | 2025-07-06 22:56:07,913 - NewsBot - ERROR - jobs - Exception while handling an update:
robopost-bot  | Traceback (most recent call last):
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1309, in process_update
robopost-bot  |     await coroutine
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_handlers/basehandler.py", line 158, in handle_update
robopost-bot  |     return await self.callback(update, context)
robopost-bot  |   File "/app/handlers/admin_commands.py", line 88, in list_sources
robopost-bot  |     await update.message.reply_text(message, parse_mode=ParseMode.MARKDOWN_V2)
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_message.py", line 1851, in reply_text
robopost-bot  |     return await self.get_bot().send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 2988, in send_message
robopost-bot  |     return await super().send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 1099, in send_message
robopost-bot  |     return await self._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 629, in _send_message
robopost-bot  |     result = await super()._send_message(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 809, in _send_message
robopost-bot  |     result = await self._post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 697, in _post
robopost-bot  |     return await self._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
robopost-bot  |     return await super()._do_post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 726, in _do_post
robopost-bot  |     result = await request.post(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 197, in post
robopost-bot  |     result = await self._request_wrapper(
robopost-bot  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 374, in _request_wrapper
robopost-bot  |     raise exception
robopost-bot  | telegram.error.BadRequest: Can't parse entities: character '|' is reserved and must be escaped with the preceding '\'
robopost-bot  | 2025-07-06 22:58:31,469 - NewsBot - INFO - admin_commands - Manual fetch triggered by admin 676414834
(venv) rah@RAHs-iMac RoboPost2 % 
